# Generated by Django 4.2.2 on 2023-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdue', '0002_customer_customer_image_alter_bill_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
